# **COVID**
Идентификация мнений пользователей онлайновой социальной сети (на примере ситуации с COVID-19)

In [ ]:
%matplotlib inline
import pandas as pd
import numpy as np

In [ ]:
# bot5neuro other_share
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

# params

In [ ]:
# путь до файла
path = "/content/drive/MyDrive/DB/o2_BMSTU_IPU_RAN/vk_data.zip"
path_unzip = "/content"

path_comments = "/content/all_h_comments.csv"
path_likes = "/content/all_h_likes.csv"
path_posts = "/content/all_h_posts.csv"
path_vacc_comments_bmstu = "/content/h_vacc_o_comments_bmstu.csv"

In [ ]:
import zipfile
with zipfile.ZipFile(path,"r") as zip_ref:
    zip_ref.extractall(path_unzip)

In [ ]:
df1 = pd.read_csv(open(path_comments)) #, errors = 'replace'))
df2 = pd.read_csv(open(path_likes))
df3 = pd.read_csv(open(path_posts))
df4 = pd.read_csv(open(path_vacc_comments_bmstu))
# pd1 = pd.read_csv(path_comments, sep="\t", encoding="utf-8")
# pd2 = pd.read_csv(path_likes, sep="\t", encoding="utf-8")
# pd3 = pd.read_csv(path_posts, sep="\t", encoding="utf-8")
# pd4 = pd.read_csv(path_vacc_comments_bmstu, sep="\t", encoding="utf-8")

In [ ]:
print("df1.shape =", df1.shape)
print("df2.shape =", df2.shape)
print("df3.shape =", df3.shape)
print("df4.shape =", df4.shape)

df1.shape = (2423982, 9)
df2.shape = (8577599, 6)
df3.shape = (60355, 7)
df4.shape = (68630, 5)

In [ ]:
df1.head()

,Unnamed: 0,h_owner_id,h_post_id,h_comment_id,h_commenter_id,h_parent_comment_id,h_addr_comment_id,date,text
0,2464967,366cf34d87861db908a99feff782b0ab7b4b9251,352e04be1f73fd02137de7409de203acf127a3a7,a4c9938952fd8e330f9a6d3972c82e158997e9e6,8718f578dfa032dc6c06fbe35ba03fe331861d18,NaN,NaN,1584940397,"Ага !!! Границы закрыли , а деньги за тур хер!..."
1,2464968,366cf34d87861db908a99feff782b0ab7b4b9251,352e04be1f73fd02137de7409de203acf127a3a7,b179ca68adfd62fbd9d8956132a80f1052a94946,48f78f4713a6bd13859cbd17f7fc8e02385e850d,NaN,NaN,1584941036,Nan.
2,2464975,366cf34d87861db908a99feff782b0ab7b4b9251,352e04be1f73fd02137de7409de203acf127a3a7,e04483fa29ce2a62129c0e1624ac1b82fdd899e1,8fe419cd62452585b973fcf678eec191058c4fe6,a4c9938952fd8e330f9a6d3972c82e158997e9e6,a4c9938952fd8e330f9a6d3972c82e158997e9e6,1584941065,"Радуйся , что не заболел!"
3,2464976,366cf34d87861db908a99feff782b0ab7b4b9251,352e04be1f73fd02137de7409de203acf127a3a7,e95666ac68e82ea44cf6b1b7882c8d519e6e5c14,8718f578dfa032dc6c06fbe35ba03fe331861d18,a4c9938952fd8e330f9a6d3972c82e158997e9e6,NaN,1584941176,Nan.
4,2464969,366cf34d87861db908a99feff782b0ab7b4b9251,352e04be1f73fd02137de7409de203acf127a3a7,3158e5f03a0a49527162d2089c27901dd431203b,b01f307dea8b64bfbd5b65ae0ed5fe207316f927,NaN,NaN,1584942726,Чтобы поддержать мир в себе важно помнить - не...

In [ ]:
df2.head()

,Unnamed: 0,h_owner_id,h_post_id,h_obj_id,h_liker_id,obj_type
0,0,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,979aa1e3234ca33aaf5080594c323240aa3f3ead,post
1,1,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,ba30113e3fd514114d43266ab7582d51800c354c,post
2,2,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,d2cedf8808e46022dfb60948dd783d6e32dd25e0,post
3,3,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,65eb85197af98a3b8914d0ff83d838e06ab85d94,post
4,4,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,498ca99392b65e9814cd342584ccac7311179cc2,post

In [ ]:
df3.head()

,Unnamed: 0,h_owner_id,h_post_id,date,text,titles,descriptions
0,0,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,1614547215,Только 6% россиян имеют антитела к коронавирус...,«Мы еще в первой волне»: в Роспотребнадзоре ра...,Только 6% россиян имеют антитела к коронавирус...
1,1,3a40ef289520aa4f7aee712233965a92ead7f48d,d8bb762934e1fe47174f34e04edcc6da23443c57,1614538579,Только 6% россиян обладают иммунитетом к COVID...,NaN,NaN
2,2,3a40ef289520aa4f7aee712233965a92ead7f48d,17cbcc720c54ec6de91600680ba24b512fea8354,1614520996,Турция рискует превратиться в мафиозное госуда...,«Коронавирусная» амнистия: зачем Эрдоган освоб...,Турция рискует превратиться в мафиозное госуда...
3,3,3a40ef289520aa4f7aee712233965a92ead7f48d,99305c3fc0a59c62e26e1b5294198efb2c3d3cc9,1614455719,Болгария отказалась участвовать в учениях НАТО...,NaN,NaN
4,4,3a40ef289520aa4f7aee712233965a92ead7f48d,247f48db8ffb6227b3062f7c3a0c8f11f4134994,1614450019,Нехватка витамина В6 усложняет течение коронав...,NaN,NaN

In [ ]:
df4.head()

,h_owner_id,h_post_id,h_comment_id,true_label,text
0,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,eec5e145eaf5c6de4822a2c63bb50d552068b39e,NaN,"Никого же не гонят вакцинироваться, от того и ..."
1,3a40ef289520aa4f7aee712233965a92ead7f48d,d8bb762934e1fe47174f34e04edcc6da23443c57,9d439145e576026a9b4ea147d89d5c88ccba540a,NaN,"Компания по вакцинации,наверное,слабо идёт,хот..."
2,3a40ef289520aa4f7aee712233965a92ead7f48d,d8bb762934e1fe47174f34e04edcc6da23443c57,c31cbfc786b2e8c635ac113ad0741dc44b644b15,NaN,От ковида можно избавиться не только благодаря...
3,3a40ef289520aa4f7aee712233965a92ead7f48d,99305c3fc0a59c62e26e1b5294198efb2c3d3cc9,22e84d47d910158e36ff81804fbde9d6fc7eac7e,NaN,Пускай себе проводят учения члены стран НАТО. ...
4,3a40ef289520aa4f7aee712233965a92ead7f48d,99305c3fc0a59c62e26e1b5294198efb2c3d3cc9,37e1096ee856a3cccfdb6bc126ab0a7bedc7c3f9,NaN,Вот почему Зеленский просит привить американск...

In [ ]:
print("All publics = ", len(df4['h_owner_id'].unique()))

All users =  57

In [ ]:
h_owner_id_test1 = "3a40ef289520aa4f7aee712233965a92ead7f48d"
h_post_id_test1 = "08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4"
h_comment_id_test1 = "eec5e145eaf5c6de4822a2c63bb50d552068b39e"

In [ ]:
df_filter = df4['h_owner_id']. isin ([h_owner_id_test1]) 
# df4["h_owner_id" == h_owner_id_test1]

In [ ]:
df4[df_filter]

,h_owner_id,h_post_id,h_comment_id,true_label,text
0,3a40ef289520aa4f7aee712233965a92ead7f48d,08b2c3fcf5c58946ea25fc4f292f0ebd6c44fba4,eec5e145eaf5c6de4822a2c63bb50d552068b39e,NaN,"Никого же не гонят вакцинироваться, от того и ..."
1,3a40ef289520aa4f7aee712233965a92ead7f48d,d8bb762934e1fe47174f34e04edcc6da23443c57,9d439145e576026a9b4ea147d89d5c88ccba540a,NaN,"Компания по вакцинации,наверное,слабо идёт,хот..."
2,3a40ef289520aa4f7aee712233965a92ead7f48d,d8bb762934e1fe47174f34e04edcc6da23443c57,c31cbfc786b2e8c635ac113ad0741dc44b644b15,NaN,От ковида можно избавиться не только благодаря...
3,3a40ef289520aa4f7aee712233965a92ead7f48d,99305c3fc0a59c62e26e1b5294198efb2c3d3cc9,22e84d47d910158e36ff81804fbde9d6fc7eac7e,NaN,Пускай себе проводят учения члены стран НАТО. ...
4,3a40ef289520aa4f7aee712233965a92ead7f48d,99305c3fc0a59c62e26e1b5294198efb2c3d3cc9,37e1096ee856a3cccfdb6bc126ab0a7bedc7c3f9,NaN,Вот почему Зеленский просит привить американск...
...,...,...,...,...,...
46059,3a40ef289520aa4f7aee712233965a92ead7f48d,720373037da9b1d81ce87dec747cf538fc9a3eab,1cb70353b89f306c62a342ed2b60a7dbe7a464c7,NaN,Мысль не изменить. Спешка нужна при ловле блох...
46060,3a40ef289520aa4f7aee712233965a92ead7f48d,720373037da9b1d81ce87dec747cf538fc9a3eab,c0b43b50572b84e7a03cd08cd1229693201003a6,NaN,Ну ни вы и никто пока не может со 100% уверенн...
46061,3a40ef289520aa4f7aee712233965a92ead7f48d,720373037da9b1d81ce87dec747cf538fc9a3eab,209d9832178cbcfb879cac1eb0c582ea4839e192,1.0,"Ну понятно,своё здоровье дорого.Ну не нравятся..."
46062,3a40ef289520aa4f7aee712233965a92ead7f48d,87d1124ee5db77ec642d6b77ca2fc8ed71904f83,5c338cae3d0c21e26b82046c768d875601fe2eec,0.0,Странно а что он не привился сказочной вакцино...
46063,3a40ef289520aa4f7aee712233965a92ead7f48d,822cd9850f0ab87caca855202bc263d0d70ae611,1d8d53ffeb4d3ccc6cf7708147bd5bb6dd02d6b9,NaN,А что не привился сказочной вакциной путина.

# Experiments